table dim_date
	lineageTag: fabd0001-a001-4a1a-9c1a-000000000101

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: fabd0001-a001-4a1a-9c1a-000000000102
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fabd0001-a001-4a1a-9c1a-000000000103
		summarizeBy: none
		sourceColumn: Year

	column MonthNo
		dataType: int64
		formatString: 0
		lineageTag: fabd0001-a001-4a1a-9c1a-000000000104
		summarizeBy: none
		sourceColumn: MonthNo

	column Month
		dataType: string
		lineageTag: fabd0001-a001-4a1a-9c1a-000000000105
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthSort

		changedProperty = SortByColumn

	column MonthSort
		dataType: int64
		formatString: 0
		lineageTag: fabd0001-a001-4a1a-9c1a-000000000106
		summarizeBy: none
		sourceColumn: MonthSort

	column Week
		dataType: dateTime
		formatString: Long Date
		lineageTag: fabd0001-a001-4a1a-9c1a-000000000107
		summarizeBy: none
		sourceColumn: Week

	partition dim_date = m
		mode: import
		source =
				let
				    Source = List.Dates(#date(2023,1,1), 3000, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Date", type datetime}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added MonthNo" = Table.AddColumn(#"Added Year", "MonthNo", each Date.Month([Date]), Int64.Type),
				    #"Added Month" = Table.AddColumn(#"Added MonthNo", "Month", each Text.Upper(Text.Start(Date.MonthName([Date]), 3)) & " " & Number.ToText(Date.Year([Date])), type text),
				    #"Added MonthSort" = Table.AddColumn(#"Added Month", "MonthSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    #"Added Week" = Table.AddColumn(#"Added MonthSort", "Week", each DateTime.From(Date.StartOfWeek([Date], Day.Monday)), type datetime)
				in
				    #"Added Week"

	annotation PBI_ResultType = Table

