table dim_product
	lineageTag: 88d5aea3-d879-42c2-999c-0f4126e6d385

	column product_id
		dataType: string
		lineageTag: e1e5c6d0-217b-4543-9238-9014511ebc01
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 5ac28bf9-81b5-4b28-a671-7bd4c6e6b121
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: 0340bb39-fe70-4877-9a37-473ab7857ff9
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Fab WIP & Cycle Time Analytics\fabdata\dim_product.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", type text}, {"product_name", type text}, {"family", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

